//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalWebsite.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyPersonalBlogEntities1 : DbContext
    {
        public MyPersonalBlogEntities1()
            : base("name=MyPersonalBlogEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<todolist> todolist { get; set; }
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<Bacariqlar> Bacariqlar { get; set; }
        public virtual DbSet<Elaqe> Elaqe { get; set; }
        public virtual DbSet<haqqimda> haqqimda { get; set; }
        public virtual DbSet<Hobbi> Hobbi { get; set; }
        public virtual DbSet<Sertifikatlar> Sertifikatlar { get; set; }
        public virtual DbSet<sosyalmedya> sosyalmedya { get; set; }
        public virtual DbSet<Tecrube> Tecrube { get; set; }
        public virtual DbSet<tehsil> tehsil { get; set; }
    }
}
