//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalWebsite.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sertifikatlar
    {
        public int İD { get; set; }
        public string Açıqlama { get; set; }
        public string Tarix { get; set; }
    }
}
