//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalWebsite.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class todolist
    {
        public int ID { get; set; }
        public string Tasks { get; set; }
        public string Deadline { get; set; }
    }
}
